import { NextRequest, NextResponse } from "next/server";
import { getStepRuns, selectStepRun, getStepSelections, deleteStepFromRun, clearStepRuns, skipStep, unskipStep, getSkippedSteps, loadStore } from "@/lib/db";
import { stopActiveProcess } from "@/app/api/generate/route";
import { execSync } from "child_process";
import fs from "fs";
import path from "path";

const PROJECT_ROOT = path.resolve(process.cwd(), "..");

// Map step IDs to their output subfolder names
const STEP_TO_FOLDER: Record<string, string> = {
  generate_script: "script",
  plan_scenes: "scenes",
  design_characters: "characters",
  generate_clips: "clips",
  validate_quality: "quality",
  add_audio: "audio",
  compose_episode: "compose",
  publish: "publish",
};

// Map step IDs to root-level files they produce (copied/symlinked from timestamped subfolder)
const STEP_ROOT_FILES: Record<string, string[]> = {
  generate_script: ["script.yaml"],
  plan_scenes: ["scenes_breakdown.yaml"],
  design_characters: ["characters.yaml"],
  add_audio: ["audio_plan.yaml"],
  compose_episode: ["edit_plan.yaml"],
  publish: ["publish.yaml"],
};

const IS_WINDOWS = process.platform === "win32";

/**
 * Kill a process by PID (used when the in-memory process map doesn't have it,
 * e.g., after HMR or server restart).
 */
function killByPid(pid: number): void {
  try {
    if (IS_WINDOWS) {
      execSync(`taskkill /pid ${pid} /T /F`, { stdio: "ignore" });
    } else {
      process.kill(pid, "SIGKILL");
    }
  } catch {
    // Process may have already exited
  }
}

function getRunOutputPath(storyId: number, episodeId: number, stepId: string, outputDir: string | null): string | null {
  const store = loadStore();
  const story = store.stories.find((s: { id: number }) => s.id === storyId);
  const episode = store.episodes.find((e: { id: number }) => e.id === episodeId);
  if (!story || !episode) return null;

  const folder = STEP_TO_FOLDER[stepId];
  if (!folder) return null;

  const baseDir = path.join(PROJECT_ROOT, "data", "stories", story.slug, "episodes", String(episode.episode_number), folder);

  if (outputDir) {
    const dir = path.join(baseDir, outputDir);
    return fs.existsSync(dir) ? dir : null;
  }

  // Fallback: if outputDir is null but there's only one timestamped subfolder, use it
  if (fs.existsSync(baseDir)) {
    const entries = fs.readdirSync(baseDir).filter((e) => /^\d{8}_\d{6}$/.test(e));
    if (entries.length === 1) {
      return path.join(baseDir, entries[0]);
    }
  }
  return null;
}

function deleteRunArtifacts(storyId: number, episodeId: number, stepId: string, outputDir: string | null, startedAt?: string | null): void {
  // For design_characters, also delete story-level character YAMLs + avatars generated in this run
  if (stepId === "design_characters") {
    deleteCharacterRunFiles(storyId, episodeId, outputDir);
  }

  // For publish step, also delete generated output files (final/gallery, final/poster, final/video, story poster, publish.yaml)
  if (stepId === "publish") {
    const store = loadStore();
    const story = store.stories.find((s: { id: number }) => s.id === storyId);
    const episode = store.episodes.find((e: { id: number }) => e.id === episodeId);
    if (story && episode) {
      const epDir = path.join(PROJECT_ROOT, "data", "stories", story.slug, "episodes", String(episode.episode_number));
      const storyDir = path.join(PROJECT_ROOT, "data", "stories", story.slug);
      // Delete final output subdirectories generated by publish
      for (const sub of ["final/gallery", "final/poster", "final/video"]) {
        const subDir = path.join(epDir, sub);
        if (fs.existsSync(subDir)) {
          fs.rmSync(subDir, { recursive: true, force: true });
        }
      }
      // Delete story-level poster directory (new: poster/, legacy: posters/)
      for (const posterDir of ["poster", "posters"]) {
        const storyPosterDir = path.join(storyDir, posterDir);
        if (fs.existsSync(storyPosterDir)) {
          fs.rmSync(storyPosterDir, { recursive: true, force: true });
        }
      }
      // Delete root publish.yaml and publish_assets.yaml
      for (const yamlFile of ["publish.yaml", "publish_assets.yaml"]) {
        const rootYaml = path.join(epDir, yamlFile);
        if (fs.existsSync(rootYaml)) {
          fs.unlinkSync(rootYaml);
        }
      }
    }
  }

  const dir = getRunOutputPath(storyId, episodeId, stepId, outputDir);
  if (dir) {
    fs.rmSync(dir, { recursive: true, force: true });
    return;
  }

  // Fallback: when output_dir is null, try to match a timestamped folder using started_at
  if (!outputDir && startedAt) {
    const store = loadStore();
    const story = store.stories.find((s: { id: number }) => s.id === storyId);
    const episode = store.episodes.find((e: { id: number }) => e.id === episodeId);
    if (story && episode) {
      const folder = STEP_TO_FOLDER[stepId];
      if (folder) {
        const baseDir = path.join(PROJECT_ROOT, "data", "stories", story.slug, "episodes", String(episode.episode_number), folder);
        if (fs.existsSync(baseDir)) {
          const entries = fs.readdirSync(baseDir).filter((e) => /^\d{8}_\d{6}$/.test(e));
          // Convert started_at (ISO UTC) to local timestamp and find nearest match (±5 min)
          const startDate = new Date(startedAt);
          let bestMatch: string | null = null;
          let bestDiff = Infinity;
          for (const entry of entries) {
            // Parse YYYYMMDD_HHMMSS as local time
            const m = entry.match(/^(\d{4})(\d{2})(\d{2})_(\d{2})(\d{2})(\d{2})$/);
            if (!m) continue;
            const entryDate = new Date(
              parseInt(m[1]), parseInt(m[2]) - 1, parseInt(m[3]),
              parseInt(m[4]), parseInt(m[5]), parseInt(m[6])
            );
            const diff = Math.abs(entryDate.getTime() - startDate.getTime());
            if (diff < 5 * 60 * 1000 && diff < bestDiff) { // Within 5 minutes
              bestDiff = diff;
              bestMatch = entry;
            }
          }
          if (bestMatch) {
            const matchedDir = path.join(baseDir, bestMatch);
            fs.rmSync(matchedDir, { recursive: true, force: true });
            return;
          }
        }
      }
    }
  }

  // Last-resort fallback for legacy runs with no output_dir and no started_at:
  // delete the base folder itself
  if (!outputDir) {
    const store = loadStore();
    const story = store.stories.find((s: { id: number }) => s.id === storyId);
    const episode = store.episodes.find((e: { id: number }) => e.id === episodeId);
    if (story && episode) {
      const folder = STEP_TO_FOLDER[stepId];
      if (folder) {
        const baseDir = path.join(PROJECT_ROOT, "data", "stories", story.slug, "episodes", String(episode.episode_number), folder);
        if (fs.existsSync(baseDir)) {
          fs.rmSync(baseDir, { recursive: true, force: true });
        }
      }
    }
  }
}

/**
 * Extract character slugs from a characters.yaml file.
 */
function extractSlugsFromFile(filePath: string): string[] {
  if (!fs.existsSync(filePath)) return [];
  try {
    const content = fs.readFileSync(filePath, "utf-8");
    const slugs: string[] = [];
    for (const m of Array.from(content.matchAll(/^\s*slug:\s*(.+)$/gm))) {
      const slug = m[1].trim().replace(/^["']|["']$/g, "");
      if (slug) slugs.push(slug);
    }
    return slugs;
  } catch {
    return [];
  }
}

/**
 * Read the characters.yaml from a design_characters run subfolder, extract character slugs,
 * and delete the corresponding story-level YAML and avatar files — but only if the character
 * was NOT present in any other design_characters run (i.e., it was first introduced in this run).
 */
function deleteCharacterRunFiles(storyId: number, episodeId: number, outputDir: string | null): void {
  const store = loadStore();
  const story = store.stories.find((s: { id: number }) => s.id === storyId);
  const episode = store.episodes.find((e: { id: number }) => e.id === episodeId);
  if (!story || !episode) return;

  // Find the run's characters.yaml to get the list of slugs
  const runDir = getRunOutputPath(storyId, episodeId, "design_characters", outputDir);
  if (!runDir) return;

  const thisRunSlugs = extractSlugsFromFile(path.join(runDir, "characters.yaml"));
  if (thisRunSlugs.length === 0) return;

  // Collect slugs from all OTHER design_characters runs (to know which to preserve)
  const preserveSlugs = new Set<string>();
  const epFolder = path.join(PROJECT_ROOT, "data", "stories", story.slug, "episodes", String(episode.episode_number), "characters");
  if (fs.existsSync(epFolder)) {
    for (const entry of fs.readdirSync(epFolder)) {
      const entryDir = path.join(epFolder, entry);
      if (!fs.statSync(entryDir).isDirectory()) continue;
      // Skip the run being deleted
      if (outputDir && entry === outputDir) continue;
      for (const slug of extractSlugsFromFile(path.join(entryDir, "characters.yaml"))) {
        preserveSlugs.add(slug);
      }
    }
  }

  const storyCharsDir = path.join(PROJECT_ROOT, "data", "stories", story.slug, "characters");
  const avatarsDir = path.join(storyCharsDir, "avatars");

  for (const slug of thisRunSlugs) {
    // Keep characters that exist in other runs
    if (preserveSlugs.has(slug)) continue;
    // Validate slug has no path traversal
    if (slug.includes("..") || slug.includes("/") || slug.includes("\\")) continue;

    const yamlFile = path.join(storyCharsDir, `${slug}.yaml`);
    if (fs.existsSync(yamlFile)) fs.unlinkSync(yamlFile);

    const avatarFile = path.join(avatarsDir, `${slug}.png`);
    if (fs.existsSync(avatarFile)) fs.unlinkSync(avatarFile);
  }

  // Only delete root-level characters.yaml if no other runs remain
  if (preserveSlugs.size === 0) {
    const epDir = path.join(PROJECT_ROOT, "data", "stories", story.slug, "episodes", String(episode.episode_number));
    const rootCharsYaml = path.join(epDir, "characters.yaml");
    if (fs.existsSync(rootCharsYaml)) fs.unlinkSync(rootCharsYaml);
  }
}

/** Delete root-level YAML files produced by a step (only when clearing ALL runs for that step). */
function deleteStepRootFiles(storyId: number, episodeId: number, stepId: string): void {
  const rootFiles = STEP_ROOT_FILES[stepId];
  if (!rootFiles) return;

  const store = loadStore();
  const story = store.stories.find((s: { id: number }) => s.id === storyId);
  const episode = store.episodes.find((e: { id: number }) => e.id === episodeId);
  if (!story || !episode) return;

  const epDir = path.join(PROJECT_ROOT, "data", "stories", story.slug, "episodes", String(episode.episode_number));
  for (const file of rootFiles) {
    const filePath = path.join(epDir, file);
    if (fs.existsSync(filePath)) {
      fs.unlinkSync(filePath);
    }
  }
}

export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url);
  const storyId = parseInt(searchParams.get("story_id") || "0", 10);
  const episodeId = parseInt(searchParams.get("episode_id") || "0", 10);
  const stepId = searchParams.get("step");

  if (!storyId || !episodeId) {
    return NextResponse.json({ error: "story_id and episode_id required" }, { status: 400 });
  }

  // If step is specified, return runs for that step
  if (stepId) {
    const runs = await getStepRuns(storyId, episodeId, stepId);
    return NextResponse.json({ runs });
  }

  // Otherwise return selections and success status for all steps
  const selections = await getStepSelections(storyId, episodeId);
  const skipped = getSkippedSteps(storyId, episodeId);
  return NextResponse.json({ selections, skipped });
}

export async function POST(req: NextRequest) {
  const body = await req.json();
  const { story_id, episode_id, step_id, run_id } = body;

  if (!story_id || !episode_id || !step_id || !run_id) {
    return NextResponse.json({ error: "story_id, episode_id, step_id, run_id required" }, { status: 400 });
  }

  await selectStepRun(story_id, episode_id, step_id, run_id);
  return NextResponse.json({ success: true });
}

export async function DELETE(req: NextRequest) {
  const { searchParams } = new URL(req.url);
  const storyId = parseInt(searchParams.get("story_id") || "0", 10);
  const episodeId = parseInt(searchParams.get("episode_id") || "0", 10);
  const stepId = searchParams.get("step_id") || "";
  const runId = searchParams.get("run_id");

  if (!storyId || !episodeId || !stepId) {
    return NextResponse.json({ error: "story_id, episode_id, step_id required" }, { status: 400 });
  }

  if (runId) {
    const runIdNum = parseInt(runId, 10);
    // Stop any active process for this run before deleting
    const stoppedInMemory = stopActiveProcess(runIdNum);
    // Get run info to find artifact folder before deleting from DB
    const runs = await getStepRuns(storyId, episodeId, stepId);
    const run = runs.find((r) => r.run_id === runIdNum);
    if (run) {
      // If in-memory stop failed but run has a PID and is still "running", kill by PID
      if (!stoppedInMemory && run.pid && run.status === "running") {
        killByPid(run.pid);
      }
      deleteRunArtifacts(storyId, episodeId, stepId, run.output_dir, run.started_at);
    }
    await deleteStepFromRun(storyId, episodeId, stepId, runIdNum);
  } else {
    // Clear all: stop any running processes, then delete artifacts
    const runs = await getStepRuns(storyId, episodeId, stepId);
    for (const run of runs) {
      stopActiveProcess(run.run_id);
      if (run.pid && run.status === "running") {
        killByPid(run.pid);
      }
      deleteRunArtifacts(storyId, episodeId, stepId, run.output_dir, run.started_at);
    }
    deleteStepRootFiles(storyId, episodeId, stepId);
    await clearStepRuns(storyId, episodeId, stepId);
  }

  return NextResponse.json({ success: true });
}

export async function PATCH(req: NextRequest) {
  const body = await req.json();
  const { story_id, episode_id, step_id, action } = body;

  if (!story_id || !episode_id || !step_id) {
    return NextResponse.json({ error: "story_id, episode_id, step_id required" }, { status: 400 });
  }

  if (action === "skip") {
    const label = body.label || step_id;
    await skipStep(story_id, episode_id, step_id, label);
    return NextResponse.json({ success: true });
  }

  if (action === "unskip") {
    unskipStep(story_id, episode_id, step_id);
    return NextResponse.json({ success: true });
  }

  return NextResponse.json({ error: "Unknown action" }, { status: 400 });
}
